/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "stm32f1xx.h"

/*
 * SysTick_Handler interrupt handler
 */
int SysTick_TASK = 0;
void SysTick_Handler(void)
{
	// Do stuff
	SysTick_TASK = 1;
}

int main(void)
{
	// Set Bit 4 to enable GPIOC clock
	RCC->APB2ENR |= (1 << 4);

	// Set Bit 2 to enable GPIOA clock
	RCC->APB2ENR |= (1 << 2);

	// Make GPIOE Pin13 output
	GPIOC->CRH &= 0xFF0FFFFF;
	GPIOC->CRH |= 0x00200000;

	// Make GPIOA Pin A7, A6, A5
	GPIOA->CRL &= 0x000FFFFF;
	GPIOA->CRL |= 0x222FFFFF;


	// Reset GPIOC Pin13
	GPIOC->ODR |= (1 << 13);
	GPIOA->ODR |= (1 << 5);
	GPIOA->ODR |= (1 << 6);
	GPIOA->ODR |= (1 << 7);

	// variável que muda a sequência
	int passo = 0;

	/*System Tick Configuration
	 * Initializes the System Timer and its interrupt, and starts the System Tick Timer.
     * Counter is in free running mode to generate periodic interrupts.
	 */
	uint32_t ticks = 1000000; //ticks  Number of ticks between two interrupts, should be less than 0xFFFFFFUL = 16777216  (24bits)
	if ((ticks - 1UL) <= 0xFFFFFFUL)
	{
		 /* set reload register */
		SysTick->LOAD  = (uint32_t)(ticks - 1UL);

		/* set Priority for Systick Interrupt */
		//NVIC_SetPriority (SysTick_IRQn, (1UL << __NVIC_PRIO_BITS) - 1UL);

		SysTick->VAL   = 0UL;			/* Load the SysTick Counter Value */

		SysTick->CTRL  = (0 << 2) |		/* 0 -> SysTick_Clock = AHB/8 */
						 (1 << 1) |	 	/* Enable SysTick IRQ and SysTick Timer */
						 (1 << 0);
	}

	while(1)
	{
		if(SysTick_TASK)
		{
			SysTick_TASK = 0;
			switch(passo){
				case 0: // VERMELHO
					GPIOA->ODR &= ~(1 << 5);
					passo = 1;
					break;
				case 1: // VERDE
					GPIOA->ODR |= (1 << 5);
					GPIOA->ODR &= ~(1 << 6);
					passo = 2;
					break;
				case 2: // AZUL
					GPIOA->ODR |= (1 << 6);
					GPIOA->ODR &= ~(1 << 7);
					passo = 3;
					break;
				case 3: // AMARELO
					GPIOA->ODR |= (1 << 7);
					GPIOA->ODR &= ~(1 << 5);
					GPIOA->ODR &= ~(1 << 6);
					passo = 4;
					break;
				case 4: // CIANO
					GPIOA->ODR |= (1 << 5);
					GPIOA->ODR &= ~(1 << 7);
					passo = 5;
					break;
				case 5: // ROXO
					GPIOA->ODR |= (1 << 6);
					GPIOA->ODR &= ~(1 << 5);
					passo = 6;
					break;
				case 6: // BRANCO
					GPIOA->ODR &= ~(1 << 6);
					passo = 7;
					break;
				case 7: // APAGADO
					GPIOA->ODR |= (1 << 5);
					GPIOA->ODR |= (1 << 6);
					GPIOA->ODR |= (1 << 7);
					passo = 0;
					break;
			}

			GPIOA->ODR ^= ~(1 << 5);
			GPIOA->ODR ^= ~(1 << 6);
			GPIOA->ODR ^= ~(1 << 7);

		}
	}
}
